config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :likes
  devise_for :users, :controllers => { :registrations => :registrations }
  devise_scope :user do
    authenticated :user do
      root to: 'pics#index'
    end
    unauthenticated :user do
      root to: 'devise/registrations#new', as: :unauthenticated_root
    end
  end

  resources :pics do
    resources :likes
    resources :comments
  end

  resources :users, only: [:show]

  patch '/users/:id', to: 'users#update'

  post '/follower/:id', to: 'follows#create', as: :follower 
  delete '/follower/:id', to: 'follows#destroy'

  delete '/pics/:pic_id/likes/:id', to: 'likes#destroy', as: :destroy_like_path

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :pic
  belongs_to :user
end

app/models/follow.rb
class Follow < ApplicationRecord
    belongs_to :follower, class_name: 'User'
    belongs_to :following, class_name: 'User'
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :pic
  belongs_to :user
end

app/models/pic.rb
class Pic < ApplicationRecord
    belongs_to :user
    has_many :likes
    has_many :comments
    accepts_nested_attributes_for :comments

    #For Paperclip gem
    has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
    validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ApplicationRecord
  has_many  :pics, dependent: :destroy
  has_many :likes
  has_many :comments

  has_many :followed_users, foreign_key: :follower_id, class_name: 'Follow'
  has_many :followings, through: :followed_users

  has_many :following_users, foreign_key: :following_id, class_name: 'Follow'
  has_many :followers, through: :following_users

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  #For Paperclip gem
  has_attached_file :picture, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/picture/:style/missing.png"
  validates_attachment_content_type :picture, content_type: /\Aimage\/.*\z/

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
        # Prevent CSRF attacks by raising an exception.
    # For APIs, you may want to use :null_session instead.
    protect_from_forgery with: :exception

    before_action :configure_permitted_parameters, if: :devise_controller?

    protected

         def configure_permitted_parameters
              devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:username, :email, :password)}

              devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:username, :email, :password, :current_password)}
         end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

    def create
        @pic = Pic.find(comments_params[:pic_id])
        @comment = Comment.create(comments_params)
        redirect_to pic_path(@pic)
    end

    def comments_params
        params.require(:comment).permit(:content, :pic_id, :user_id)
    end
end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController

    def create
        if already_followed?
            flash[:notice] = "Sorry can only like once"
        else #can follow the user
            @following = User.find(params[:id])
            Follow.create(follower_id: current_user.id, following_id: @following.id)
        end
        
        redirect_to @following
    end

    def destroy
        @following = User.find(params[:id])
        @follow = Follow.find_by(follower_id: current_user.id, following_id: @following.id)
        @follow.destroy

        redirect_to @following
    end

    private
    # Checks if a particular user was already followed
    def already_followed?
        Follow.where(follower_id: current_user.id, following_id: params[:id]).exists?
        # byebug
    end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    before_action :find_post

    def create
        if already_liked?
            flash[:notice] = "Sorry, can't like more than once!"
          else #can like
            @pic.likes.create(user_id: current_user.id)
            redirect_to pic_path(@pic)
        end
    end

    def destroy
        @like = Like.find_by(user_id: current_user.id)
        @like.destroy

        redirect_to pic_path(params[:pic_id])
    end

    private

    def find_post
        @pic = Pic.find(params[:pic_id])
    end

    #check if a picture was already like
    def already_liked?
        Like.where(user_id: current_user.id, pic_id:
        params[:pic_id]).exists?
    end
end

app/controllers/pics_controller.rb
class PicsController < ApplicationController
    before_action :find_pic, only: [:show, :edit, :update, :destroy]

    def index
        @pics = Pic.all
    end

    def show 
        @comment = Comment.new
        @like = Like.find_by(pic_id: @pic.id, user_id: current_user.id)
    end

    def new
       @pic = current_user.pics.build
    end

    def create
        @pic = current_user.pics.build(pic_params)

        if (@pic.save)
            redirect_to @pic, notice: "The picture has been posted!"
        else
            render "new"
        end
    end

    def edit
    end

    def update
    
        if (@pic.update(pic_params))
            redirect_to @pic, notice: "The picture was updated!"
        else
            render "edit"
        end
    end

    def destroy
            @pic.destroy
            redirect_to root_path
    end

private

    def pic_params
        params.require(:pic).permit(:title, :description, :image, comments_attributes: [:content])
    end

    def find_pic
        @pic = Pic.find(params[:id])
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

    protected
  
      def after_update_path_for(resource)
        #redirect to edit page, instead of index by default
        # see: https://github.com/heartcombo/devise/wiki/How-To:-Customize-the-redirect-after-a-user-edits-their-profile
        edit_user_registration_path(resource)
      end
  end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def show
        # @user = current_user
        @user = User.find(params[:id])
    end

    def update
        @user = User.find(params[:id])

        if (@user.update(user_params)) #if user exits update them
            redirect_to edit_user_registration_path
        else
            render "edit"
        end
        # byebug

    end

    private

    def user_params
        params.require(:user).permit(:username, :email, :picture)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/pics_helper.rb
module PicsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <style>
      .button { background-color: rgb(62, 74, 247); color: white;}
      .marg {margin-left:1% !important;}
      a:hover {text-decoration: none; color:red;}
      .right {text-align: right; margin-left:26%;}

      #fixed_nav {
        z-index: 5;     /*place in front of pictures so they go behind, not in front*/
        overflow: hidden;
        position: fixed; /* Set the navbar to fixed position */
        top: 0; /* Position the navbar at the top of the page */
        width: 100%; /* Full width */

      }

      #pads{
        padding-top:5%;
        padding-bottom:5%;
        padding-right:5%;
        padding-left:5%;
      }

      .vertical_banner {
        border: 1px solid #E9E3DD;
        float: left;
        height: 210px;
        margin: 2px;
        padding: 4px 2px 10px 10px;
        text-align: left;
        width: 117px;
        position:relative;
    }
    
    #bottom_link{
       position:absolute;                  /* added */
       bottom:0;                           /* added */
       left:0;                           /* added */
    }
    </style>

  </head>

  <!--Navigation-->
  <body class="marg">
   <% current_uri = request.env['PATH_INFO'] %> 
   <% if user_signed_in? %>
     <nav class="navbar navbar bg-light" id="fixed_nav" style="box-shadow: 1px 2px 4px rgba(0, 0, 0, .1);">
      <div class="container">
        <%= link_to image_tag("https://entrecodigoyletras.files.wordpress.com/2016/05/instagram-logo.png?w=656", width:"20%"), pics_path %>
        <%= link_to "📷", current_user, class:"right" %>
        <%= link_to "👤", edit_user_registration_path %> 
        <%= link_to "📭", new_pic_path %>
        <%= link_to "🚪", destroy_user_session_path, method: :delete %> 
      </div>
     </nav>

    <% else %>

    <nav class="navbar navbar bg-light" style= "box-shadow: 1px 2px 4px rgba(0, 0, 0, .1);">
      <div style="text-align:right;">
        <%= link_to "Log in", new_user_session_path %> -
        <%= link_to "Sign up", new_user_registration_path %>  
      </div>
    </nav>
  
   <% end %>
    <div style="margin-top: 5%; z-index:1">
    <%= yield %>
  </div>


    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

app/views/pics/_form.html.erb
#Form for posting a pic
<div style="color:rgba(90, 113, 247, 0.685); size:10;">
<%= simple_form_for(@pic) do |f| %>
    <%= f.input :image %> 
    <%= f.input :title %>
    <%= f.input :description %>
    <div style="text-align: center;"><%= f.button :submit, class:"button" %></div>
<% end %>
</div>

app/views/pics/edit.html.erb
<div class="container">
     <div class="row" style="margin-left:25%;">
      <div class="col-md-8" style="vertical-align:center; box-shadow: 1px 2px 4px rgba(0, 0, 0, .2);">
                 <h3 style="text-align: center; margin-top:2%">Edit a picture</h3>
     
                 <%= render 'form' %> 
     
            <div style="text-align: center;"> <%= link_to "Cancel", pic_path %> </div>
     
       </div>
     </div>
</div>

app/views/pics/index.html.erb
<div class="container">
    <h5 style="color:grey; margin-top:3%">Explore</h5>
    <div class="container">
    <div class="row">
    
    <!-- <% @pics.all.each do |pic|%>
        <div class="card">
            <img class="card-img-top" src=<%="#{pic.image.url}" %> alt="Card image cap">
            <%= link_to image_tag("#{pic.image.url}", alt:"#{pic.title}", width:"70%", height: "60%"), pic %> 
            <li><%= link_to pic.title, pic %></li>
        </div>
        <% end %>  -->
        
      <% sorted_pics = @pics.order('created_at DESC') %>
        <% sorted_pics.all.each do |pic|%>
            <div class="col-sm-4 h-100 py-2 px-2">
              <div class="card card-body h-100 mt-4" >
                <%= link_to image_tag("#{pic.image.url}", alt:"#{pic.title}", width:"100%", height: "100%"), pic %>
                <!-- <div><%= link_to pic.title, pic %></div> -->
                <div style="text-align: center;">
                    ❤ <%= pic.likes.count.to_i %>
                </div>
              </div>
            </div>
        <% end %> 
      </div>
    </div>
</div>

app/views/pics/new.html.erb
<div   class ="container" style="width: 50%; margin-left: 40%; margin-top: 5%">
    <div class="col-md-6" style="vertical-align:center; box-shadow: 1px 2px 4px rgba(0, 0, 0, .2);">
        <img src="https://entrecodigoyletras.files.wordpress.com/2016/05/instagram-logo.png?w=656" width="80%" alt="Instagram logo" />

        <h3 style="text-align: center;">Post a picture</h3>

            <%= render 'form' %> 

            <%= link_to 'Back', root_path %>

      </h1>
    </div>
</div>

app/views/pics/show.html.erb
<div style="text-align: center; margin-top:1%">
    <%= link_to "Back", root_path %> 
    <!-- Check if the current user is the one who posted the pic -->
    <% if (current_user.username === @pic.user.username) %>
      | <%= link_to "Edit", edit_pic_path %> |
        <%= link_to "Delete", pic_path, method: :delete, data: {confirm: "Are you sure?"} %> 
    <% end %>
</div>

<div class="col-sm-14 h-100 py-2 px-6" style="margin-left:5%;">
    <div class="card-group" height="10%">
        
        <div class="card">
            <img src=<%="#{@pic.image.url}"%> alt=<%=@pic.title%> width="100%" height="100%"/>
            <small>Description: <%= @pic.title %></small>
        </div>
        
        <!-- Picture & description -->
        <div class="card scrollBox" style="margin-right:10%; padding-top:1%">
                <h6 style="margin-left:5%">
                    <%= link_to "#{@pic.user.username}", @pic.user %> 
                    <div style="margin-left:10%;"><%= @pic.description %></div>
                </h6>
        
                <!-- Comment Box -->
                <% @pic.comments.each do |comment| %>
                <h6 style="margin-left: 15%"> 
                    <%= link_to "#{comment.user.username}", comment.user %> 
                    &nbsp; <%= comment.content %> 
                </h6>
                <% end %>
 
      
                <div class="vertical banner"> 
                 <div id="bottom_link" style="margin-left:5%;">
                                   <!-- <input type="image" src="https://upload.wikimedia.org/wikipedia/commons/4/4a/Twemoji12_1f5a4.svg" width="17%" /> -->
                  <!-- LIKING & UNLIKING -->
                  <%  if (@like.nil?) %>
                        <%= link_to image_tag("https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSdeBlfsvnZ5sZw7W1dWGT7D67P3XdBAqA3ivkrCBl15fu6JBt7", width:"11%"), pic_likes_path(@pic), method: :post %>
                        <p><%= @pic.likes.count %> <%= (@pic.user.likes.count) == 1 ? 'Like' : 'Likes'%></p>
                  <%  else %>
                  <!-- "/pics/#{@pic.id}/likes/#{@like.id}" -->
                        
                        <%= link_to image_tag("https://upload.wikimedia.org/wikipedia/commons/4/4a/Twemoji12_1f5a4.svg", width:"17%"), "/pics/#{@pic.id}/likes/#{@like.id}", method: :delete %>
                        <p><%= @pic.likes.count %> <%= (@pic.user.likes.count) == 1 ? 'Like' : 'Likes'%></p>
                   <% end %>
                 </div>
                </div>    
    
        </div>
    </div>
</div>
<div class="col-sm-14 h-100 py-2 px-6" style="margin-left:5%; margin-right:52%;">
                <!-- COMMENT BOX -->
                <%= form_for @comment do |f| %>        
                            <%= f.text_area  :content, value: " ", style:"width:100%" %>
                            <%= f.hidden_field :pic_id, :value => params[:id] %>
                            <%= f.hidden_field :user_id, :value => current_user.id %>
                <%= f.submit "Post", style:"margin-bottom:1%" %>  
                <% end %>
</div>

app/views/users/show.html.erb
    <!--  USER'S SHOW PAGE -->

   <!-- PROFILE DETAILS -->
<div class='row right-padded'>
    <!-- Profile picture goes here -->
    <div class='col-md-2' style="padding-left: 4%; padding-top: 2%;">
      <% correct_user = User.find_by(id: params[:id]) %>
      <img class='profilePic' src=<%="#{correct_user.picture.url}"%> alt='Profile picture' width="100%" />
    </div>
    <div class='col-md-10 left-padded'>
      <h4>
        <%= correct_user.username %>
        <span class = 'button-div' style="word-spacing: 4px; margin-top: 3%; margin-bottom: 1%;">
        <% if (correct_user != current_user) %> <!-- Hide Follow button if on own show page -->
          <% if (Follow.where(follower_id: current_user.id, following_id: params[:id]).exists?) %>
            <%= button_to "Unfollow", follower_path(correct_user.id), method: :delete, :class => 'follow-button' %>
          <% else %>
            <%= button_to "Follow", follower_path(correct_user.id), method: :post, :class => 'follow-button'  %>
          <% end  %>
        <% end  %>
      </span>
      </h4>
      <h6 style="word-spacing: 4px; margin-bottom: 3%;"><b><%= correct_user.pics.count.to_i %></b> posts &nbsp;&nbsp;&nbsp; <b><%= correct_user.followers.count.to_i %></b> Followers &nbsp;&nbsp;&nbsp; <b><%= correct_user.followers.count.to_i %></b> Following </h6>

      <h6><b><%= @user.username %></b></h6>
      <h6><%= correct_user.email %></h6>
    </div>
</div> 
    
    <br />
    <br />
    <!-- User's list of posts -->

<div class="container">
    <div class="container">
    <div class="row">
      <!-- sort pictures in descending order of creation and display them -->  
      <% sorted_pics = @user.pics.order('created_at DESC') %>
        <% sorted_pics.all.each do |pic|%>
            <div class="col-sm-4 h-100 py-2 px-2">
              <div class="card card-body h-100 mt-4" >
                <%= link_to image_tag("#{pic.image.url}", alt:"#{pic.title}", width:"100%", height: "100%"), pic %>
                <!-- <div><%= link_to pic.title, pic %></div> -->
                <div style="text-align: center;">
                    ❤ <%= pic.likes.count.to_i %>
                </div>
              </div>
            </div>
        <% end %> 
      </div>
    </div>
</div>


<!--
    <div class="container" style="left:20%; position: absolute;">
     <div class="col-md-8">
        <div class="card">
        <% @user.pics.each do |pic| %>
            <%= link_to image_tag("#{pic.image.url}", alt:"#{pic.title}", width:"100%", height: "100%"), pic %>
        <% end %>
     </div>
    </div>
    
</div> -->